<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\FreqIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FftSharp" Version="2.2.0" />
    <PackageReference Include="FFTVIS" Version="1.0.0" />
    <PackageReference Include="H.NotifyIcon" Version="2.3.0" />
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2" />
    <PackageReference Include="ZstdNet" Version="1.4.5" />
	  
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x64\libzstd.dll" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x64\libzstd.dll" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x86\libzstd.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x64\libzstd.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x86\libzstd.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x86\libzstd.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x64\libzstd.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x64\libzstd.dll" />
    <None Remove="Images\icon.png" />
    <None Remove="Images\icon2.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="C:\Users\jhset\.nuget\packages\zstdnet\1.4.5\build\x64\libzstd.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\icon2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LibMaterial.NET">
      <HintPath>C:\Users\jhset\Desktop\LibMaterial-main\.NET\bin\Release\net6.0-windows\LibMaterial.NET.dll</HintPath>
    </Reference>
    <Reference Include="NAudio">
      <HintPath>..\..\NAudio-per-process\NAudio\bin\Release\net6.0-windows\NAudio.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.Asio">
      <HintPath>..\..\NAudio-per-process\NAudio\bin\Release\net6.0-windows\NAudio.Asio.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.Core">
      <HintPath>..\..\NAudio-per-process\NAudio\bin\Release\net6.0-windows\NAudio.Core.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.Midi">
      <HintPath>..\..\NAudio-per-process\NAudio\bin\Release\net6.0-windows\NAudio.Midi.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.Wasapi">
      <HintPath>..\..\NAudio-per-process\NAudio\bin\Release\net6.0-windows\NAudio.Wasapi.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.WinForms">
      <HintPath>..\..\NAudio-per-process\NAudio\bin\Release\net6.0-windows\NAudio.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.WinMM">
      <HintPath>..\..\NAudio-per-process\NAudio\bin\Release\net6.0-windows\NAudio.WinMM.dll</HintPath>
    </Reference>
  </ItemGroup>
	
</Project>
